config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks'}

  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[show create update destroy], shallow: true
      end
    end
  end

  concern :voteable do
    member do
      post :up_rating
      delete :un_rating
      post :down_rating
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :attachments, only: :destroy
  resources :badges, only: :index

  resources :questions, concerns: [:voteable, :commentable] do
    member do
      post :subscribe
      delete :unsubscribe
    end
    resource :subscription, only: %i[create destroy]
    resources :answers, concerns: [:voteable, :commentable], only: %i[create update destroy], shallow: true do
      patch :make_best, on: :member
    end
  end

  get :search, to: 'searches#index'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :bigint(8)        not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint(8)        not null
#

class Question < ApplicationRecord
  include Voteable
  include Commentable

  scope :today, -> { where(created_at: Date.today.beginning_of_day..Date.today.end_of_day ) }

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  belongs_to :user
  has_one :badge, dependent: :destroy

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :badge, reject_if: proc { |attributes| attributes['image'].blank? }

  has_many_attached :files

  validates :title, :body, presence: true

  after_create :calculate_reputation

  after_create :subscribe_author

  def subscribe(current_user)
    subscriptions.create!(user_id: current_user.id)
  end

  def unsubscribe(current_user)
    subscriptions.find_by(user_id: current_user.id).destroy
  end

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def subscribe_author
    subscriptions.create!(user_id: user.id)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  authorize_resource except: %i[update destroy]

  def index
    @questions = Question.all

    render json: @questions
  end

  def show
    render json: question
  end

  def create
    @question = Question.new(question_params.merge(user: current_user))

    if @question.save
      render json: @question
    else
      render_json_errors(@question)
    end
  end

  def update
    authorize! :update, question

    if question.update(question_params)
      render json: question
    else
      render_json_errors(@question)
    end
  end

  def destroy
    authorize! :update, question

    question.destroy
  end

  private

  def question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def render_json_errors(resource)
    render json: resource.errors.full_messages, status: :unprocessable_entity
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  after_action :publish_question, only: :create

  authorize_resource except: %i[update destroy]

  def index
    @questions = Question.all
    gon.question = question
  end

  def show
    @answer = question.answers.new
    @subscription = question.subscriptions.new(user: current_user)

    gon.current_user = current_user
    gon.question = question
  end

  def new
    @question = Question.new
    @question.badge = Badge.new
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      redirect_to question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    authorize! :update, question
    question.update(question_params)
  end

  def destroy
    authorize! :destroy, question
    question.destroy
    redirect_to questions_path, notice: 'Question delete successfully'
  end

  private

  helper_method :question

  def publish_question
    return if question.errors.any?
    ActionCable.server.broadcast(
      'questions',
       ApplicationController.render(partial: 'questions/question', locals: { question: question })
    )
  end

  def question
    @question ||= params[:id] ? Question.with_attached_files.find(params[:id]) : Question.new
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: [:id, :name, :url, :_destroy], badge_attributes: [:name, :image])
  end
end

app/views/questions/_form.html.slim
= form_with model: question, **form_params do |f|
  = f.label :title, 'Question title'
  = f.text_field :title, class: 'form-control', rows: 4
  = f.label :body, 'Question body'
  = f.text_area :body, class: 'form-control', rows: 8
  = f.label :files
  = f.file_field :files, multiple: true, direct_upload: true
  = render 'links/form', f: f
  p Badge:
  p
    = f.fields_for :badge do |badge|
      .nested-fields
        p
          = badge.label :name, 'Badge name'
          = badge.text_field :name
        p
          = badge.label :image, 'Badge image'
          = badge.file_field :image
  = f.submit 'Save question', class: 'btn btn-primary'

app/views/questions/_question.html.slim
tr
  td = "Answers: #{question.answers.count}"
  td= link_to question.title, question_path(question)
  td = "Author:  #{question.user.email}"

app/views/questions/_question_show.html.slim
- if can?(:create, @subscription)
  = link_to 'Subscribe', question_subscription_path(question), method: :post
- if can?(:destroy, @subscription)
  = link_to 'Unsubscribe', question_subscription_path(question), method: :delete
h1 = question.title
= question.body
= render 'votes/show', resource: question
= render 'attachments/files', resource: question

.badge
  - if question.badge.present?
    p Badge:
    = image_tag(question.badge.image, height: "100", width: "100")

.links-body
  p Links:
  ul
    - question.links.each  do |link|
      - if link.gist_link?
        - link.gist_contents.each do |content|
          -cache content do
            li=content
      -else
        -cache link do
          li= link_to link.name, link.url, target: '_blank'

.question-comments
  | Comments:
  = render question.comments
  = render 'comments/form', commentable: question

- if can?(:update, question)
  => link_to 'Delete question', question_path(question), method: :delete, data: {confirm: 'Are you sure?'}
  => link_to 'Edit question', '#', class: 'edit-question-link', data: { question_id: question.id }
  = render partial: 'form', locals: { question: question, form_params: { class: 'hidden', html: { id: "edit-question-#{question.id}" } } }

- if user_signed_in?
  = link_to 'Add comment', '#', class: 'button-question-comment', data: { question_id: question.id }

app/views/questions/index.html.slim
div.text-right
  = link_to 'Ask question', new_question_path, class: 'btn btn-primary'

div.text-left
  - if current_user&.badges.present?
    = link_to 'My badges', badges_path, class: 'btn btn-primary'

- cache collection_cache_key_for :question do
  table.table.table-hover.questions
    = render @questions

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= render partial: 'form', locals: { question: @question, form_params: { local: true } }

app/views/questions/show.html.slim
.question_errors
  = render 'shared/errors', resource: question

.answer_errors
  = render 'shared/errors', resource: @answer

.comment_errors
  = render 'shared/errors', resource: @comment

-cache question do
  .question
    = render 'question_show'

  .answers
    = render question.answers

  - if current_user
    = form_with model: [question, @answer], class: 'new-answer' do |f|
      = f.label :body
      = f.text_area :body, class: 'form-control', rows: 8
      = f.label :files
      = f.file_field :files, multiple: true
      = render 'links/form', f: f
      = f.submit 'Give answer'

app/views/questions/update.js.erb
$('.question_errors').html('<%= render 'shared/errors', resource: question %>');

<% if !question.errors.present? %>
  $('.question').html('<%= j render 'question_show' %>');
<% end %>