config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks'}

  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: %i[index] do
        get :me, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        resources :answers, only: %i[show create update destroy], shallow: true
      end
    end
  end

  concern :voteable do
    member do
      post :up_rating
      delete :un_rating
      post :down_rating
    end
  end

  concern :commentable do
    resources :comments, only: :create
  end

  resources :attachments, only: :destroy
  resources :badges, only: :index

  resources :questions, concerns: [:voteable, :commentable] do
    member do
      post :subscribe
      delete :unsubscribe
    end
    resource :subscription, only: %i[create destroy]
    resources :answers, concerns: [:voteable, :commentable], only: %i[create update destroy], shallow: true do
      patch :make_best, on: :member
    end
  end

  get :search, to: 'searches#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :bigint(8)        not null, primary key
#  body        :text
#  question_id :bigint(8)        not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint(8)        not null
#  best        :boolean          default(FALSE), not null
#

class Answer < ApplicationRecord
  include Voteable
  include Commentable

  default_scope { order(best: :desc) }

  after_create_commit :broadcast_answer

  has_many :links, dependent: :destroy, as: :linkable
  belongs_to :question, touch: true
  belongs_to :user

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  has_many_attached :files

  validates :body, presence: true

  after_create :send_report

  def make_best!
    ActiveRecord::Base.transaction do
      question.answers.update_all(best: false)
      update!(best: true)
      set_badge! if question.badge.present?
    end
  end

  private

  def send_report
    Services::Report.new.send_report(self)
  end

  def set_badge!
    question.badge.update!(user: user)
  end

  def broadcast_answer
    ActionCable.server.broadcast "question/#{question.id}/answers", answer_data
  end

  def answer_data
    data = {}
    data[:answer] = self
    data[:files] = files_data
    data[:links] = links_data
    data[:rating] = rating

    data
  end

  def files_data
    data =[]
    files.each do |file|
      data << {
        file_name: file.filename.to_s,
        file_id: file.id,
        file_url: Rails.application.routes.url_helpers.rails_blob_path(file, only_path: true) }
    end

    data
  end

  def links_data
    data = []
    links.each do |link|
      links_data = { link_name: link.name, link_url: link.url }
      links_data[:gist_content] = link.gist_contents  if link.gist_link?
      data << links_data
    end

    data
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!

  authorize_resource except: %i[update destroy]

  def create
    @answer = question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def edit
  end

  def update
    authorize! :update, answer
    answer.update(answer_params)

    @question = answer.question
  end

  def destroy
    authorize! :destroy, answer
    answer.destroy
  end

  def make_best
    authorize! :make_best, answer
    answer.make_best!
  end

  private

  def chanel
    "question/#{question.id}/answers"
  end

  def question
    @question ||= params[:question_id] ? Question.find(params[:question_id]) : answer.question
  end

  def answer
    @answer ||= params[:id] ? Answer.with_attached_files.find(params[:id]) : question.answers.new
  end

  helper_method :answer, :question

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:id, :name, :url, :_destroy])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  authorize_resource

  def show
    @answer = Answer.find(params[:id])
    render json: @answer
  end

  def create
    @answer = question.answers.new(answer_params.merge(user: current_user))
    if @answer.save
      render json: @answer
    else
      render json: @answer.errors.full_messages, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, answer

    if answer.update(answer_params)
      render json: answer
    else
      render_json_errors(@answer)
    end
  end

  def destroy
    authorize! :update, answer

    answer.destroy
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def question
    @question = Question.find(params[:question_id])
  end

  def answer
    @answer = Answer.find(params[:id])
  end

  def render_json_errors(resource)
    render json: resource.errors.full_messages, status: :unprocessable_entity
  end
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  - cache answer do
    li[id="answer_#{answer.id}"]
      => answer.body
      = render 'attachments/files', resource: answer
      - if can?(:make_best, answer)
        => link_to 'Best answer', make_best_answer_path(answer), method: :patch, remote: true
      = render 'votes/show', resource: answer
      .links-body
        p Links:
        ul
          - answer.links.each  do |link|
            - if link.gist_link?
              - link.gist_contents.each do |content|
                -cache content do
                  li= content
            - else
              -cache link do
                li= link_to link.name, link.url, target: '_blank'

      .answer-comments
        | Comments:
        = render answer.comments
        = render 'comments/form', commentable: answer

      - if answer.best?
        ' This is best answer
      - if can?(:update, answer)
        => link_to 'Delete answer', answer_path(answer), method: :delete, data: { confirm: 'Are you sure?' }, remote: true
        = link_to 'Edit answer', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

        = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
          = f.label :body, 'Your answer'
          = f.text_area :body
          = f.label :files
          = f.file_field :files, multiple: true, direct_upload: true
          = render 'links/form', f: f
          = f.submit 'Save answer'

      - if user_signed_in?
        = link_to 'Add comment', '#',class: 'button-answer-comment', data: { answer_id: answer.id }

app/views/answers/create.js.erb
<% if answer.errors.present? %>
  $('.answer_errors').html('<%= render 'shared/errors', resource: answer %>');
<% else %>
  $('.answers').append('<%= j render answer %>');
  $('new_answer, #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('#answer_'+ <%= @answer.id %>).remove();

app/views/answers/make_best.js.erb
$('.answers').html('<%= j render question.answers %>');

app/views/answers/update.js.erb
<% if answer.errors.present? %>
  $('.answer_errors').html('<%= render 'shared/errors', resource: answer %>');
<% else %>
  $('#answer_'+ <%= answer.id %>).replaceWith('<%= j render answer %>');
<% end %>